<?php

require_once dirname(__FILE__) . '/class.php';

/**
 * Test class for RomanNumerals.
 * Generated by PHPUnit on 2012-09-20 at 09:12:42.
 */
class RomanNumeralsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var RomanNumerals
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
	$this->object = new RomanNumerals;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
	
    }

    /**
     * @dataProvider setAanDataRoman
     * @covers RomanNumerals::toRoman
     * @todo Implement testToRoman().
     */
    public function testToRoman($roman, $result) {
	
	//$this->assertEquals($this->object->toRoman('3888888') , 'mmmdccclxxxvMMMDCCCLXXXVIII');
	$this->assertEquals($this->object->toRoman($result), $roman);
    }

    /**
     * @dataProvider setAanDataRoman
     * @covers RomanNumerals::toDecimal
     * @todo Implement testToDecimal().
     */
    public function testToDecimal($roman, $result) {
	
	//$this->assertEquals($this->object->toDecimal('mmmdccclxxxvMMMDCCCLXXXVIII'), '3888888');
	$this->assertEquals($this->object->toDecimal($roman), $result);
    }
    
    
    public function setAanDataRoman(){
	
	return array(
		array('mmmdccclxxxvMMMDCCCLXXXVIII','3888888' ),
		array('mmmcmxcixCMXCIX','3999999' ),
		array('X','10' ),
		array('XX','20' ),
		array('L','50' ),
		array('LXXX','80' ),
		array('II','2' ),
		array('','0' ),
	);
    }
}

